# Generated by Django 4.2.1 on 2023-11-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_my_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='my_username',
        ),
    ]
