version: '3'
services:
  web:
    image: pokemons
    build:
      context: "~/data"
    command: gunicorn area.wsgi:application --bind 0.0.0.0:80
    volumes:
      - .:/app  # Монтируйте текущую директорию в контейнер
    ports:
      - 80:80
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Dagad582
      - POSTGRES_DB=main
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data: