# Generated by Django 4.2.1 on 2023-10-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200116_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('pokemon_id', models.IntegerField(default=1)),
                ('attack', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='fightroom',
            name='enemy_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_pokemon', to='polls.pokemon'),
        ),
        migrations.AddField(
            model_name='fightroom',
            name='your_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_pokemon', to='polls.pokemon'),
        ),
    ]
