# Generated by Django 4.2.1 on 2023-10-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_fightroom_pokemon_delete_new_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightroom',
            name='game_ended',
            field=models.BooleanField(default=False),
        ),
    ]
