# Generated by Django 4.2.1 on 2023-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_fightroom_you_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='img',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.TextField(default=0),
        ),
    ]
