# Generated by Django 4.2.1 on 2023-10-05 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_pokemon_height_pokemon_img_pokemon_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightroom',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
