# Generated by Django 4.2.1 on 2023-10-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_fightroom_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fightroom',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fightroom',
            name='rounds',
            field=models.IntegerField(default=1),
        ),
    ]
