# Generated by Django 4.2.1 on 2023-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_fightroom_created_at_fightroom_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightroom',
            name='logs',
            field=models.TextField(default=''),
        ),
    ]
