# Generated by Django 4.2.1 on 2023-12-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_fightroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightroom',
            name='user',
            field=models.TextField(blank=True, default='Анонимный польователь', null=True),
        ),
    ]
