# Generated by Django 4.2.1 on 2023-12-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_fightroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightroom',
            name='logs',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
